Improve WillowApplication to support custom error handlers...
ba-st/Willow pull request #171
Opened 2020-07-05 19:09 UTC by jvanecek

...on different deployment modes. 
A proposed solution for #170

2020-07-06 11:39 UTC, mtabacman submitted a review, later dismissed

2020-07-06 12:16 UTC, gcotelli commented on source/BaselineOfWillow/BaselineOfWillow.class.st
> +		group: 'Tests' with: #('Willow-Tests' 'Willow-Core-Development-Support')
Why not in the `Tools` group also? If you're using Willow as a dependency don't need the Tests group but having the Tools one is handy for development.

2020-07-06 12:18 UTC, gcotelli requested changes
See the comment on the baseline groups :)

2020-07-15 19:07 UTC, mtabacman approved these changes

2020-07-15 19:17 UTC, gcotelli approved these changes

2020-07-15 19:22 UTC, merged